(function () {
  "use strict";

  const STORAGE_KEY = "dyco.settings.v1";
  const BRIDGE_SOURCE = "DYCO_BRIDGE";
  const RESPONSE_TYPE = "DYCO_PLAYER_RESPONSE";
  const REQUEST_TYPE = "DYCO_REQUEST_PLAYER_RESPONSE";
  const PRIME_TYPE = "DYCO_PRIME_CAPTIONS";
  const DEFAULT_SETTINGS = {
    enabled: false,
    primaryKey: "",
    secondaryKey: "",
    fontScale: 1,
    backgroundOpacity: 0.72,
    panelOpen: false,
    panelCollapsed: false,
    uiLanguage: "en",
    overlayDefaultOffMigrated: false
  };

  const UI_TEXT = {
    en: {
      title: "Dual captions",
      primary: "Primary caption",
      secondary: "Secondary caption",
      overlay: "Overlay",
      refresh: "Refresh",
      fontSize: "Font size",
      opacity: "Background opacity",
      none: "None",
      autoGenerated: "auto-generated",
      autoTranslate: "YouTube auto-translate",
      expand: "Expand panel",
      collapse: "Collapse panel"
    },
    "zh-Hant": {
      title: "雙字幕",
      primary: "主要字幕",
      secondary: "第二字幕",
      overlay: "顯示字幕",
      refresh: "重新整理",
      fontSize: "字體大小",
      opacity: "背景透明度",
      none: "不選擇",
      autoGenerated: "自動產生",
      autoTranslate: "YouTube 自動翻譯",
      expand: "展開面板",
      collapse: "收合面板"
    }
  };

  const LANGUAGE_NAMES = {
    en: { en: "English", "zh-Hant": "英文" },
    ja: { en: "Japanese", "zh-Hant": "日文" },
    zh: { en: "Chinese", "zh-Hant": "中文" },
    "zh-Hant": { en: "Traditional Chinese", "zh-Hant": "繁體中文" },
    "zh-TW": { en: "Traditional Chinese", "zh-Hant": "繁體中文" },
    "zh-HK": { en: "Traditional Chinese", "zh-Hant": "繁體中文" },
    "zh-Hans": { en: "Simplified Chinese", "zh-Hant": "簡體中文" },
    "zh-CN": { en: "Simplified Chinese", "zh-Hant": "簡體中文" }
  };

  const parser = window.DYCO.captionParser;
  const timeSync = window.DYCO.timeSync;

  const state = {
    settings: { ...DEFAULT_SETTINGS },
    video: null,
    sync: null,
    tracks: [],
    translations: [],
    options: [],
    primaryCaptions: [],
    secondaryCaptions: [],
    primaryCursor: -1,
    secondaryCursor: -1,
    activePrimaryKey: "",
    activeSecondaryKey: "",
    lastPrimaryText: "",
    lastSecondaryText: "",
    lastSignature: "",
    fetchCache: new Map(),
    lastVideoSrc: "",
    currentVideoId: "",
    observer: null,
    saveTimer: 0,
    responseRequestTimer: 0,
    buttonRetryTimer: 0
  };

  const dom = {};

  init();

  async function init() {
    injectPlayerResponseBridge();
    createUi();
    bindMessages();

    const storedSettings = (await chrome.storage.local.get(STORAGE_KEY))[STORAGE_KEY];
    state.settings = {
      ...DEFAULT_SETTINGS,
      ...storedSettings
    };
    if (!storedSettings || !storedSettings.overlayDefaultOffMigrated) {
      state.settings.enabled = false;
      state.settings.overlayDefaultOffMigrated = true;
      chrome.storage.local.set({ [STORAGE_KEY]: state.settings });
    }
    applySettingsToUi();
    state.currentVideoId = getVideoId();

    window.addEventListener("message", (event) => {
      if (event.source !== window || !event.data || event.data.source !== BRIDGE_SOURCE || event.data.type !== RESPONSE_TYPE) {
        return;
      }
      handlePlayerResponse(event.data.payload);
    });
    requestPlayerResponse();

    bindVideo();
    scheduleEnsurePlayerButton();
    state.observer = new MutationObserver(() => {
      handleVideoNavigationChange();
      bindVideo();
      scheduleEnsurePlayerButton();
      requestPlayerResponseDebounced();
    });
    state.observer.observe(document.documentElement, { childList: true, subtree: true });

    document.addEventListener("keydown", handleKeyboardShortcut, true);
    document.addEventListener("pointerdown", handleOutsidePanelPointerDown, true);
    document.addEventListener("yt-navigate-start", handleVideoNavigationChange);
    document.addEventListener("yt-navigate-finish", () => {
      handleVideoNavigationChange();
      requestPlayerResponseDebounced();
    });
    window.addEventListener("resize", () => {
      positionOverlayToVideo();
      positionPanelToVideo();
      positionFallbackButton();
    });
    window.addEventListener("scroll", handleViewportChange, { passive: true });
    if (window.visualViewport) {
      window.visualViewport.addEventListener("scroll", handleViewportChange, { passive: true });
      window.visualViewport.addEventListener("resize", handleViewportChange, { passive: true });
    }
    document.addEventListener("fullscreenchange", () => {
      positionOverlayToVideo();
      positionPanelToVideo();
      positionFallbackButton();
      ensurePlayerButton();
    });
  }

  function handleViewportChange() {
    positionOverlayToVideo();
    positionPanelToVideo();
    positionFallbackButton();
  }

  function injectPlayerResponseBridge() {
    if (document.getElementById("dyco-player-response-bridge")) return;

    const script = document.createElement("script");
    script.id = "dyco-player-response-bridge";
    script.src = chrome.runtime.getURL("bridge.js");
    script.onload = () => script.remove();
    (document.documentElement || document.head).appendChild(script);
  }

  function createUi() {
    dom.overlay = document.createElement("div");
    dom.overlay.className = "dyco-overlay";
    dom.overlay.setAttribute("role", "status");
    dom.overlay.setAttribute("aria-live", "polite");

    dom.primaryLine = document.createElement("div");
    dom.primaryLine.className = "dyco-line dyco-line-primary";
    dom.secondaryLine = document.createElement("div");
    dom.secondaryLine.className = "dyco-line dyco-line-secondary";
    dom.overlay.append(dom.primaryLine, dom.secondaryLine);

    dom.panel = document.createElement("div");
    dom.panel.className = "dyco-panel dyco-panel-hidden";
    dom.panel.innerHTML = `
      <div class="dyco-panel-header">
        <div class="dyco-panel-title" data-i18n="title">Dual captions</div>
        <div class="dyco-panel-actions">
          <button class="dyco-icon-button" type="button" data-action="language" title="Switch language">中</button>
          <button class="dyco-icon-button" type="button" data-action="collapse" title="Collapse panel">-</button>
        </div>
      </div>
      <div class="dyco-panel-body">
        <div class="dyco-field">
          <label for="dyco-primary" data-i18n="primary">Primary caption</label>
          <select id="dyco-primary" class="dyco-select"></select>
        </div>
        <div class="dyco-field">
          <label for="dyco-secondary" data-i18n="secondary">Secondary caption</label>
          <select id="dyco-secondary" class="dyco-select"></select>
        </div>
        <div class="dyco-row dyco-refresh-row">
          <button class="dyco-button" type="button" data-action="refresh" data-i18n="refresh">Refresh</button>
        </div>
        <div class="dyco-field">
          <label for="dyco-font" data-i18n="fontSize">Font size</label>
          <input id="dyco-font" class="dyco-range" type="range" min="0.4" max="3" step="0.05">
        </div>
        <div class="dyco-field">
          <label for="dyco-opacity" data-i18n="opacity">Background opacity</label>
          <input id="dyco-opacity" class="dyco-range" type="range" min="0" max="0.95" step="0.05">
        </div>
        <div class="dyco-status" aria-live="polite"></div>
        <div class="dyco-panel-footer">
          <label class="dyco-switch">
            <span data-i18n="overlay">Overlay</span>
            <input id="dyco-enabled" type="checkbox">
          </label>
        </div>
      </div>
    `;

    dom.primarySelect = dom.panel.querySelector("#dyco-primary");
    dom.secondarySelect = dom.panel.querySelector("#dyco-secondary");
    dom.enabledToggle = dom.panel.querySelector("#dyco-enabled");
    dom.fontRange = dom.panel.querySelector("#dyco-font");
    dom.opacityRange = dom.panel.querySelector("#dyco-opacity");
    dom.status = dom.panel.querySelector(".dyco-status");
    dom.languageButton = dom.panel.querySelector('[data-action="language"]');
    dom.collapseButton = dom.panel.querySelector('[data-action="collapse"]');
    dom.refreshButton = dom.panel.querySelector('[data-action="refresh"]');

    dom.primarySelect.addEventListener("change", () => updateSelection("primaryKey", dom.primarySelect.value));
    dom.secondarySelect.addEventListener("change", () => updateSelection("secondaryKey", dom.secondarySelect.value));
    dom.enabledToggle.addEventListener("change", () => {
      state.settings.enabled = dom.enabledToggle.checked;
      saveSettings();
      updateOverlayVisibility();
      if (state.settings.enabled) {
        state.settings.panelOpen = false;
        applyPanelOpen();
      }
      if (state.sync) state.sync.flush();
    });
    dom.fontRange.addEventListener("input", () => {
      state.settings.fontScale = Number(dom.fontRange.value);
      applyFontScale();
      saveSettings();
    });
    dom.opacityRange.addEventListener("input", () => {
      state.settings.backgroundOpacity = Number(dom.opacityRange.value);
      applyBackgroundOpacity();
      saveSettings();
    });
    dom.collapseButton.addEventListener("click", () => {
      state.settings.panelCollapsed = !state.settings.panelCollapsed;
      applyPanelCollapsed();
      saveSettings();
    });
    dom.languageButton.addEventListener("click", () => {
      state.settings.uiLanguage = state.settings.uiLanguage === "zh-Hant" ? "en" : "zh-Hant";
      applyUiLanguage();
      renderTrackOptions();
      saveSettings();
    });
    dom.refreshButton.addEventListener("click", requestPlayerResponse);

    document.documentElement.append(dom.overlay, dom.panel);
  }

  function bindMessages() {
    chrome.runtime.onMessage.addListener((message) => {
      if (!message || message.type !== "DYCO_TOGGLE") return;

      state.settings.enabled = !state.settings.enabled;
      dom.enabledToggle.checked = state.settings.enabled;
      saveSettings();
      updateOverlayVisibility();
      if (state.sync) state.sync.flush();
    });
  }

  function handleOutsidePanelPointerDown(event) {
    if (!state.settings.panelOpen) return;

    const path = typeof event.composedPath === "function" ? event.composedPath() : [];
    if (path.includes(dom.panel) || path.includes(dom.playerButton)) return;
    if (dom.panel && dom.panel.contains(event.target)) return;
    if (dom.playerButton && dom.playerButton.contains(event.target)) return;

    state.settings.panelOpen = false;
    applyPanelOpen();
    saveSettings();
  }

  function handlePlayerResponse(detail) {
    const videoId = detail && detail.videoId || "";
    if (videoId && state.currentVideoId && videoId !== state.currentVideoId) return;

    const tracks = Array.isArray(detail && detail.captionTracks) ? detail.captionTracks : [];
    const translations = Array.isArray(detail && detail.translationLanguages) ? detail.translationLanguages : [];
    const signature = JSON.stringify({
      videoId,
      tracks: tracks.map((track) => [track.languageCode, track.name, track.kind, track.vssId, track.baseUrl]),
      translations: translations.map((language) => [language.languageCode, language.name])
    });

    if (signature === state.lastSignature) return;
    state.lastSignature = signature;
    state.tracks = tracks;
    state.translations = translations;
    state.options = buildOptions(tracks, translations);
    state.fetchCache.clear();

    renderTrackOptions();
    ensureValidSelections();
    loadSelectedCaptions();
  }

  function handleVideoNavigationChange() {
    const nextVideoId = getVideoId();
    if (nextVideoId === state.currentVideoId) return;

    state.currentVideoId = nextVideoId;
    state.lastSignature = "";
    state.tracks = [];
    state.translations = [];
    state.options = [];
    state.primaryCaptions = [];
    state.secondaryCaptions = [];
    state.primaryCursor = -1;
    state.secondaryCursor = -1;
    state.settings.enabled = false;
    dom.enabledToggle.checked = false;
    state.fetchCache.clear();
    renderTrackOptions();
    clearRenderedText();
    setStatus(nextVideoId ? "Loading captions for this video." : "No YouTube video detected.");
    saveSettings();
    requestPlayerResponseDebounced();
  }

  function buildOptions(tracks, translations) {
    const options = [];
    const seen = new Set();

    tracks.forEach((track, index) => {
      const key = `track:${track.vssId || track.languageCode || index}:${index}`;
      options.push({
        key,
        type: "track",
        label: `${track.languageCode || "unknown"} - ${track.name || track.languageCode || "Caption"}`,
        track
      });
    });

    const source = tracks.find((track) => track.isTranslatable) || tracks[0];
    if (source) {
      translations.forEach((language) => {
        const languageCode = language.languageCode;
        if (!languageCode || seen.has(languageCode)) return;
        seen.add(languageCode);
        options.push({
          key: `translate:${languageCode}`,
          type: "translation",
          label: `${languageCode} - ${language.name || languageCode} (YouTube auto-translate)`,
          track: {
            ...source,
            sourceLanguageCode: source.languageCode,
            languageCode,
            name: language.name || languageCode,
            translationLanguageCode: languageCode
          }
        });
      });
    }

    return options.sort(compareCaptionOptions);
  }

  function compareCaptionOptions(left, right) {
    const leftRank = getCaptionOptionRank(left);
    const rightRank = getCaptionOptionRank(right);
    for (let index = 0; index < leftRank.length; index += 1) {
      if (leftRank[index] !== rightRank[index]) return leftRank[index] - rightRank[index];
    }
    return getOptionLabel(left).localeCompare(getOptionLabel(right));
  }

  function getCaptionOptionRank(option) {
    const track = option.track || {};
    return [
      option.type === "track" && track.kind === "asr" ? 0 : 1,
      getLanguagePriority(track.languageCode),
      option.type === "track" ? 0 : 1
    ];
  }

  function getLanguagePriority(languageCode) {
    const normalized = normalizeLanguageCode(languageCode);
    if (normalized === "en") return 0;
    if (normalized === "ja") return 1;
    if (normalized === "zh-Hant") return 2;
    if (normalized === "zh-Hans") return 3;
    if (normalized === "zh") return 4;
    return 20;
  }

  function normalizeLanguageCode(languageCode) {
    if (!languageCode) return "";
    if (languageCode === "zh-Hant" || languageCode === "zh-TW" || languageCode === "zh-HK") return "zh-Hant";
    if (languageCode === "zh-Hans" || languageCode === "zh-CN" || languageCode === "zh-SG") return "zh-Hans";
    return languageCode.split("-")[0];
  }

  function getUiText() {
    return UI_TEXT[state.settings.uiLanguage] || UI_TEXT.en;
  }

  function getOptionLabel(option) {
    if (!option || !option.track) return "";

    const track = option.track;
    const text = getUiText();
    const languageCode = track.languageCode || "";
    const languageName = getLanguageName(languageCode, track.name || languageCode);
    const suffixes = [];

    if (track.kind === "asr") suffixes.push(text.autoGenerated);
    if (option.type === "translation") suffixes.push(text.autoTranslate);

    return `${languageCode || "unknown"} - ${languageName}${suffixes.length ? ` (${suffixes.join(", ")})` : ""}`;
  }

  function getLanguageName(languageCode, fallback) {
    const language = state.settings.uiLanguage;
    const names = LANGUAGE_NAMES[languageCode] || LANGUAGE_NAMES[normalizeLanguageCode(languageCode)];
    return names && names[language] || fallback;
  }

  function renderTrackOptions() {
    const fragmentA = document.createDocumentFragment();
    const fragmentB = document.createDocumentFragment();
    const text = getUiText();
    const emptyA = new Option(text.none, "");
    const emptyB = new Option(text.none, "");
    fragmentA.append(emptyA);
    fragmentB.append(emptyB);

    for (const option of state.options) {
      const label = getOptionLabel(option);
      fragmentA.append(new Option(label, option.key));
      fragmentB.append(new Option(label, option.key));
    }

    dom.primarySelect.replaceChildren(fragmentA);
    dom.secondarySelect.replaceChildren(fragmentB);
    dom.primarySelect.value = state.settings.primaryKey;
    dom.secondarySelect.value = state.settings.secondaryKey;
  }

  function ensureValidSelections() {
    const keys = new Set(state.options.map((option) => option.key));
    if (!keys.has(state.settings.primaryKey)) {
      const preferredPrimary = getPreferredPrimaryOption();
      state.settings.primaryKey = preferredPrimary ? preferredPrimary.key : "";
    }
    if (!keys.has(state.settings.secondaryKey)) {
      state.settings.secondaryKey = getDefaultSecondaryKey(state.settings.primaryKey);
    }
    state.settings.secondaryKey = getAutoSecondaryKey(state.settings.primaryKey, state.settings.secondaryKey);

    dom.primarySelect.value = state.settings.primaryKey;
    dom.secondarySelect.value = state.settings.secondaryKey;
    saveSettings();

    if (state.options.length === 0) {
      setStatus("No YouTube captions found for this video.");
    } else {
      setStatus(`${state.options.length} YouTube caption options available.`);
    }
  }

  async function loadSelectedCaptions() {
    const loadVideoId = state.currentVideoId;
    state.activePrimaryKey = state.settings.primaryKey;
    state.activeSecondaryKey = state.settings.secondaryKey;
    state.primaryCaptions = [];
    state.secondaryCaptions = [];
    state.primaryCursor = -1;
    state.secondaryCursor = -1;
    clearRenderedText();

    const primaryOption = getOption(state.settings.primaryKey);
    const secondaryOption = resolveSecondaryOption(getOption(state.settings.secondaryKey), primaryOption);

    try {
      const primary = await fetchCaptions(primaryOption);
      const secondary = await fetchCaptions(secondaryOption);

      if (loadVideoId !== state.currentVideoId || state.activePrimaryKey !== state.settings.primaryKey || state.activeSecondaryKey !== state.settings.secondaryKey) {
        return;
      }

      state.primaryCaptions = primary;
      state.secondaryCaptions = secondary;
      const hasSelection = Boolean(primaryOption || secondaryOption);
      if (!primary.length && !secondary.length && hasSelection) {
        setStatus("YouTube returned empty caption data for the selected track(s). Native CC may be unavailable.");
      } else if (!primary.length && !secondary.length) {
        setStatus("Select one or two YouTube caption tracks.");
      } else {
        setStatus(`Captions loaded: primary ${primary.length}, secondary ${secondary.length}.`);
      }
      if (state.sync) state.sync.flush();
    } catch (error) {
      setStatus("Could not load selected captions.");
      console.warn("[Dual YouTube Caption Overlay] Caption load failed", error);
    }
  }

  async function fetchCaptions(option) {
    if (!option || !option.track) return [];

    const url = parser.makeCaptionUrl(option.track);
    if (!url) return [];
    if (state.fetchCache.has(url)) return state.fetchCache.get(url);

    const promise = (async () => {
      let directError = null;
      let captions = [];

      try {
        captions = await fetchAndParseCaptionUrl(url);
      } catch (error) {
        directError = error;
      }

      if (captions.length) return captions;

      primeYouTubeCaptions(option.track);
      const capturedUrl = await waitForCapturedTimedText(option.track);
      if (!capturedUrl) {
        if (directError) throw directError;
        return captions;
      }

      const resolvedUrl = option.track.translationLanguageCode
        ? parser.makeTranslatedCapturedUrl(capturedUrl, option.track.translationLanguageCode)
        : parser.makeCaptionUrl({
          ...option.track,
          baseUrl: capturedUrl
        });

      return fetchAndParseCaptionUrl(resolvedUrl);
    })()
      .catch((error) => {
        state.fetchCache.delete(url);
        throw error;
      });

    state.fetchCache.set(url, promise);
    return promise;
  }

  function resolveSecondaryOption(secondaryOption, primaryOption) {
    if (!secondaryOption || secondaryOption.type !== "translation" || !isAuthorProvidedTrack(primaryOption)) {
      return secondaryOption;
    }

    return {
      ...secondaryOption,
      track: {
        ...primaryOption.track,
        languageCode: secondaryOption.track.languageCode,
        name: secondaryOption.track.name,
        sourceLanguageCode: primaryOption.track.languageCode,
        translationLanguageCode: secondaryOption.track.translationLanguageCode || secondaryOption.track.languageCode
      }
    };
  }

  function isAuthorProvidedTrack(option) {
    return Boolean(option && option.type === "track" && option.track && option.track.baseUrl && option.track.kind !== "asr");
  }

  async function fetchAndParseCaptionUrl(url) {
    const response = await chrome.runtime.sendMessage({
      type: "DYCO_FETCH_CAPTIONS",
      url
    });

    if (!response || !response.ok) {
      const status = response && response.status ? response.status : "network";
      const detail = response && response.error ? `: ${response.error}` : "";
      throw new Error(`Caption request failed (${status})${detail}`);
    }

    return parser.parseCaptionResponse(response.text);
  }

  function primeYouTubeCaptions(track) {
    window.postMessage({
      source: BRIDGE_SOURCE,
      type: PRIME_TYPE,
      payload: {
        languageCode: track.languageCode,
        sourceLanguageCode: track.sourceLanguageCode,
        kind: track.kind,
        vssId: track.vssId
      }
    }, window.location.origin);
  }

  async function waitForCapturedTimedText(track) {
    const videoId = getVideoId();
    const languageCode = track.sourceLanguageCode || track.languageCode || "";
    const kind = track.kind || "";

    for (let attempt = 0; attempt < 12; attempt += 1) {
      await delay(250);
      const response = await chrome.runtime.sendMessage({
        type: "DYCO_GET_CAPTURED_TIMEDTEXT",
        videoId,
        languageCode,
        kind,
        requirePot: true
      });

      if (response && response.url) return response.url;
    }

    return "";
  }

  function updateSelection(key, value) {
    state.settings[key] = value;
    if (key === "primaryKey") {
      state.settings.secondaryKey = getAutoSecondaryKey(value, state.settings.secondaryKey);
      dom.secondarySelect.value = state.settings.secondaryKey;
    }
    saveSettings();
    loadSelectedCaptions();
  }

  function getOption(key) {
    return state.options.find((option) => option.key === key);
  }

  function getPreferredPrimaryOption() {
    const manualTracks = state.options.filter((option) => option.type === "track" && option.track.kind !== "asr");
    const languagePriority = ["en", "ja", "zh", "zh-Hant", "zh-Hans"];

    for (const languageCode of languagePriority) {
      const match = manualTracks.find((option) => option.track.languageCode === languageCode);
      if (match) return match;
    }

    return manualTracks[0] || state.options.find((option) => option.type === "track") || state.options[0];
  }

  function getDefaultSecondaryKey(primaryKey) {
    const different = state.options.find((option) => option.key !== primaryKey);
    return different ? different.key : "";
  }

  function getAutoSecondaryKey(primaryKey, fallbackKey) {
    const primary = getOption(primaryKey);
    if (!primary) return fallbackKey;

    if (isEnglishOption(primary)) {
      const zhHant = findTraditionalChineseSecondary(primaryKey);
      if (zhHant) return zhHant.key;
    }

    if (isTraditionalChineseOption(primary)) {
      const english = findEnglishSecondary(primaryKey);
      if (english) return english.key;
    }

    return fallbackKey;
  }

  function isEnglishOption(option) {
    return normalizeLanguageCode(option && option.track && option.track.languageCode) === "en";
  }

  function isTraditionalChineseOption(option) {
    return normalizeLanguageCode(option && option.track && option.track.languageCode) === "zh-Hant";
  }

  function findTraditionalChineseSecondary(primaryKey) {
    return state.options.find((option) => option.key !== primaryKey && option.type === "translation" && isTraditionalChineseOption(option)) ||
      state.options.find((option) => option.key !== primaryKey && isTraditionalChineseOption(option));
  }

  function findEnglishSecondary(primaryKey) {
    return state.options.find((option) => option.key !== primaryKey && option.type === "track" && isEnglishOption(option)) ||
      state.options.find((option) => option.key !== primaryKey && isEnglishOption(option));
  }

  function bindVideo() {
    const video = document.querySelector("video");
    if (!video || video === state.video) return;

    if (state.sync) state.sync.stop();
    state.video = video;
    state.lastVideoSrc = video.currentSrc || video.src || "";
    state.sync = timeSync.createRafSync(video, renderForTime);
    state.sync.start();
    state.sync.flush();
    ensurePlayerButton();
    positionPanelToVideo();

    video.addEventListener("loadedmetadata", () => {
      const src = video.currentSrc || video.src || "";
      if (src !== state.lastVideoSrc) {
        state.lastVideoSrc = src;
        requestPlayerResponse();
      }
      if (state.sync) state.sync.flush();
    });
  }

  function renderForTime(time) {
    if (!state.settings.enabled) return;

    positionOverlayToVideo();
    positionPanelToVideo();
    positionFallbackButton();

    const primary = timeSync.findCaptionAt(state.primaryCaptions, time, state.primaryCursor);
    const secondary = timeSync.findCaptionAt(state.secondaryCaptions, time, state.secondaryCursor);
    state.primaryCursor = primary.index;
    state.secondaryCursor = secondary.index;

    const primaryText = primary.caption ? primary.caption.text : "";
    const secondaryText = secondary.caption ? secondary.caption.text : "";

    if (primaryText !== state.lastPrimaryText) {
      state.lastPrimaryText = primaryText;
      dom.primaryLine.textContent = primaryText;
    }

    if (secondaryText !== state.lastSecondaryText) {
      state.lastSecondaryText = secondaryText;
      dom.secondaryLine.textContent = secondaryText;
    }

    updateOverlayVisibility();
  }

  function clearRenderedText() {
    state.lastPrimaryText = "";
    state.lastSecondaryText = "";
    dom.primaryLine.textContent = "";
    dom.secondaryLine.textContent = "";
    updateOverlayVisibility();
  }

  function updateOverlayVisibility() {
    const hasText = Boolean(state.lastPrimaryText || state.lastSecondaryText);
    dom.overlay.classList.toggle("dyco-visible", state.settings.enabled && hasText);
    if (state.settings.enabled && hasText) {
      positionOverlayToVideo();
    }
  }

  function positionOverlayToVideo() {
    if (!state.video || !dom.overlay) return;

    const rect = state.video.getBoundingClientRect();
    if (!rect.width || !rect.height) return;

    const width = Math.min(rect.width * 0.92, 1100);
    const bottomPadding = Math.max(10, Math.min(42, rect.height * 0.055));
    const overlayHeight = dom.overlay.offsetHeight || 0;
    const top = Math.max(rect.top + 8, rect.bottom - bottomPadding - overlayHeight);

    dom.overlay.style.width = `${width}px`;
    dom.overlay.style.left = `${rect.left + rect.width / 2}px`;
    dom.overlay.style.top = `${top}px`;
    dom.overlay.style.bottom = "auto";
    dom.overlay.style.transform = "translateX(-50%)";
  }

  function ensurePlayerButton() {
    if (dom.playerButton && document.documentElement.contains(dom.playerButton)) return;

    const controls = document.querySelector(".ytp-right-controls");
    const fallbackContainer = document.querySelector(".html5-video-player") || state.video && state.video.parentElement;
    if (!controls && !fallbackContainer) {
      scheduleEnsurePlayerButton();
      return;
    }

    const useNativeControls = Boolean(controls && controls.isConnected);
    dom.playerButton = document.createElement("button");
    dom.playerButton.className = useNativeControls ? "ytp-button dyco-player-button" : "dyco-player-button dyco-player-button-floating";
    dom.playerButton.type = "button";
    dom.playerButton.title = "Dual captions";
    dom.playerButton.setAttribute("aria-label", "Dual captions");
    dom.playerButton.textContent = "Dual";
    dom.playerButton.addEventListener("click", (event) => {
      event.stopPropagation();
      state.settings.panelOpen = !state.settings.panelOpen;
      applyPanelOpen();
      saveSettings();
    });

    if (useNativeControls && mountButtonInControls(controls)) {
      dom.playerButton.className = "ytp-button dyco-player-button";
    } else {
      mountFallbackButton(fallbackContainer);
    }
    applyPanelOpen();
    positionFallbackButton();
  }

  function mountButtonInControls(controls) {
    if (!controls || !controls.isConnected) return false;

    const settingsButton = controls.querySelector(".ytp-settings-button");
    try {
      if (settingsButton && settingsButton.parentNode === controls) {
        controls.insertBefore(dom.playerButton, settingsButton);
      } else {
        controls.appendChild(dom.playerButton);
      }
      return true;
    } catch (error) {
      return false;
    }
  }

  function mountFallbackButton(fallbackContainer) {
    dom.playerButton.className = "dyco-player-button dyco-player-button-floating";
    const target = fallbackContainer && fallbackContainer.isConnected
      ? fallbackContainer
      : document.documentElement;
    target.appendChild(dom.playerButton);
  }

  function scheduleEnsurePlayerButton() {
    clearTimeout(state.buttonRetryTimer);
    state.buttonRetryTimer = setTimeout(ensurePlayerButton, 300);
  }

  function positionPanelToVideo() {
    if (!state.video || !dom.panel || !state.settings.panelOpen) return;

    const rect = state.video.getBoundingClientRect();
    if (!rect.width || !rect.height) return;

    const margin = 12;
    const width = Math.min(360, Math.max(280, rect.width * 0.34));
    dom.panel.style.width = `${width}px`;
    dom.panel.style.left = `${Math.max(8, rect.right - width - margin)}px`;
    dom.panel.style.top = `${Math.max(8, rect.bottom - dom.panel.offsetHeight - 64)}px`;
    dom.panel.style.right = "auto";
    dom.panel.style.bottom = "auto";
  }

  function positionFallbackButton() {
    if (!state.video || !dom.playerButton || !dom.playerButton.classList.contains("dyco-player-button-floating")) return;

    const rect = state.video.getBoundingClientRect();
    if (!rect.width || !rect.height) return;

    dom.playerButton.style.left = `${Math.max(8, rect.right - 72)}px`;
    dom.playerButton.style.top = `${Math.max(8, rect.bottom - 54)}px`;
  }

  function applySettingsToUi() {
    if (!UI_TEXT[state.settings.uiLanguage]) {
      state.settings.uiLanguage = "en";
    }
    dom.enabledToggle.checked = state.settings.enabled;
    dom.fontRange.value = String(state.settings.fontScale);
    dom.opacityRange.value = String(state.settings.backgroundOpacity);
    applyUiLanguage();
    applyFontScale();
    applyBackgroundOpacity();
    applyPanelOpen();
    applyPanelCollapsed();
  }

  function applyUiLanguage() {
    const text = getUiText();
    dom.panel.querySelectorAll("[data-i18n]").forEach((element) => {
      const key = element.getAttribute("data-i18n");
      if (text[key]) element.textContent = text[key];
    });
    dom.languageButton.textContent = state.settings.uiLanguage === "zh-Hant" ? "EN" : "中";
    dom.languageButton.title = state.settings.uiLanguage === "zh-Hant" ? "Switch to English" : "切換至繁體中文";
    applyPanelCollapsed();
  }

  function applyFontScale() {
    const scale = state.settings.fontScale;
    dom.overlay.style.fontSize = `clamp(${12 * scale}px, ${2.4 * scale}vw, ${72 * scale}px)`;
  }

  function applyBackgroundOpacity() {
    dom.overlay.style.setProperty("--dyco-bg-opacity", String(state.settings.backgroundOpacity));
  }

  function applyPanelCollapsed() {
    const text = getUiText();
    dom.panel.classList.toggle("dyco-collapsed", state.settings.panelCollapsed);
    dom.collapseButton.textContent = state.settings.panelCollapsed ? "+" : "-";
    dom.collapseButton.title = state.settings.panelCollapsed ? text.expand : text.collapse;
    positionPanelToVideo();
    positionFallbackButton();
  }

  function applyPanelOpen() {
    dom.panel.classList.toggle("dyco-panel-hidden", !state.settings.panelOpen);
    if (dom.playerButton) {
      dom.playerButton.classList.toggle("dyco-player-button-active", state.settings.panelOpen);
      dom.playerButton.setAttribute("aria-pressed", String(state.settings.panelOpen));
    }
    positionPanelToVideo();
  }

  function saveSettings() {
    clearTimeout(state.saveTimer);
    state.saveTimer = setTimeout(() => {
      chrome.storage.local.set({ [STORAGE_KEY]: state.settings });
    }, 150);
  }

  function setStatus(text) {
    dom.status.textContent = text;
  }

  function requestPlayerResponse() {
    window.postMessage({
      source: BRIDGE_SOURCE,
      type: REQUEST_TYPE
    }, window.location.origin);
  }

  function requestPlayerResponseDebounced() {
    clearTimeout(state.responseRequestTimer);
    state.responseRequestTimer = setTimeout(requestPlayerResponse, 300);
  }

  function handleKeyboardShortcut(event) {
    if (!event.altKey || event.shiftKey || event.ctrlKey || event.metaKey || event.code !== "KeyD") {
      return;
    }

    state.settings.enabled = !state.settings.enabled;
    dom.enabledToggle.checked = state.settings.enabled;
    saveSettings();
    updateOverlayVisibility();
    if (state.sync) state.sync.flush();
  }

  function delay(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }

  function getVideoId() {
    return new URLSearchParams(window.location.search).get("v") || "";
  }
})();
